[theme]
primaryColor = "#00F2FE"
backgroundColor = "#051621"        # Um azul petróleo bem profundo, escuro e com acabamento elegante
secondaryBackgroundColor = "#0B2538" # Um tom ligeiramente mais claro para cards e blocos
textColor = "#E0F7FA"
font = "sans serif"
